apiVersion: apps/v1
kind: Deployment
metadata:
    name: ulti_khopadi
    labels:
        app: ulti_khopadi
spec:
    replicas: 1
    selector:
      matchLabels:
        app: ulti_khopadi
    template:
      metadata:
        labels:
          app: ulti_khopadi
          tier: ulti_khopadi
      spec:
        containers:
        - name: ulti_khopadi
          image: atingupta2005/hello:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: ulti_khopadi

---
apiVersion: v1
kind: Service
metadata:
    name: ulti_khopadi
    labels:
        app: ulti_khopadi
spec:
    ports:
      - port: 5000
        targetPort: 5000
    selector:
      app: ulti_khopadi
      tier: ulti_khopadi
    type: LoadBalancer
